"""init

Revision ID: c62321512d4b
Revises: 
Create Date: 2026-06-25 00:06:39.938928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62321512d4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID primary key'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='Original filename (e.g. session_001.mcap)'),
    sa.Column('filepath', sa.String(length=1024), nullable=False, comment='Absolute path to the .mcap file on disk'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False, comment='File size in bytes at the time of discovery'),
    sa.Column('duration_s', sa.Float(), nullable=True, comment='Recording duration in seconds (populated after processing)'),
    sa.Column('stream_names', sa.JSON(), nullable=True, comment="List of stream names found in the recording (e.g. ['rgb', 'depth', 'pose'])"),
    sa.Column('status', sa.String(length=16), nullable=False, comment='unprocessed | processing | done | error'),
    sa.Column('error_msg', sa.String(length=2048), nullable=True, comment="Human-readable error detail when status='error'"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_index(op.f('ix_recordings_filename'), 'recordings', ['filename'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False, comment='queued | running | done | failed'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the job runner picks up this job'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Set when the job finishes (done or failed)'),
    sa.Column('error_msg', sa.String(length=2048), nullable=True, comment="Error detail when status='failed'"),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_recording_id'), 'jobs', ['recording_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('episode_path', sa.String(length=1024), nullable=False, comment='Absolute path to the exported episode directory'),
    sa.Column('report_path', sa.String(length=1024), nullable=True, comment='Absolute path to report.html (may be empty if QC step failed)'),
    sa.Column('health_score', sa.Float(), nullable=True, comment='0.0–1.0 QC health score from stera Evaluate (None if QC failed)'),
    sa.Column('metadata_json', sa.JSON(), nullable=False, comment='Duration, frame count, stream names, has_depth, has_pose'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_index(op.f('ix_jobs_recording_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_recordings_filename'), table_name='recordings')
    op.drop_table('recordings')
    # ### end Alembic commands ###
